awslabs/visual-asset-management-system

.prettierrc
=> chore: prettier configuration

.github/workflows/ci.yml, backend/README.rst
Not allowed to use working-directory with uses.
=> fix: updating ci.yml

.github/workflows/ci.yml
Adding CI checks for web and cdk packages
=> ci: added ci for web and cdk

backend/backend/models/assets.py, backend/tests/functions/assets/upload_asset_workflow/test_lambda_handler.py, backend/tests/functions/assets/upload_asset_workflow/test_request_handler.py, backend/tests/models/assets/test_common.py, infra/lib/api-builder.ts, infra/lib/uploadAssetWorkflowBuilder.ts, web/yarn.lock
=> feat: updates to UploadAssetWorkflow stepFunction

web/src/common/constants/fileFormats.js
Adding fbx file format support for pipelines
=> chore: adding fbx file formats for pipelines

backend/backend/models/assets.py, backend/tests/functions/assets/upload_asset_workflow/test_lambda_handler.py, backend/tests/functions/assets/upload_asset_workflow/test_request_handler.py, backend/tests/models/assets/test_common.py, infra/lib/artefacts/sample_lambda_pipeline/lambda_function.py, web/src/common/utils/utils.js, web/src/components/list/list-definitions/WorkflowExecutionListDefinition.js, web/src/components/list/list-definitions/WorkflowListDefinition.js, web/src/components/single/ViewAsset.js, web/src/components/viewers/3dViewer.js, web/src/components/viewers/ImgViewer.tsx, web/src/pages/AssetUpload.tsx, web/src/pages/AssetUpload/components.tsx, web/src/pages/AssetUpload/onSubmit.ts
- assetIds are now uuids
- assetName is assigned at upload time
- asset s3 keys are prefixed by the assetId uuid
- show generated artifacts, such as glb versions of assets, if they are present
- update example lambda pipeline for assets that contain slashes in s3 keys
- use the uploadAssetWorkflow when uploading through the upload wizard
=> Several minor fixes and updates

DeveloperGuide.md
I've documented the DynamoDB tables, their keys, and their most commonly used attributes. 
=> docs: Document the schemas of the dynamodb tables

.github/workflows/ci.yml
Updated CI script to include npm audits for infrastructure and root directories, as well as yarn audit for the web directory. Also added [cfn-nag](https://github.com/stelligent/cfn_nag) to check the infrastructure Cloudformation templates.
=> Jjbain add security tests to ci script

DeveloperGuide.md, README.md, infra/lib/constructs/amplify-config-lambda-construct.ts, infra/lib/constructs/cloudfront-s3-website-construct.ts, infra/lib/constructs/cognito-web-native-construct.ts, infra/lib/constructs/custom-cognito-config-construct.ts, infra/lib/infra-stack.ts, infra/lib/saml-config.ts, infra/lib/storage-builder.ts, infra/package.json, web/src/App.js, web/src/ConfigLoader.js, web/src/FedAuth/VAMSAuth.tsx, web/src/FedAuth/loginbox.module.css, web/src/index.js
Enables federated authentication using SAML.
=> Federated authentication using SAML.

web/src/pages/AssetUpload.tsx, web/src/pages/AssetUpload/onSubmit.ts
=> fix prettier

web/src/components/createupdate/CreateUpdateWorkflow.js, web/src/components/interactive/WorkflowEditor.js, web/src/components/selectors/AssetSelector.js
=> fix: resolves issue #68, workflow editor added extra pipelines

infra/lib/infra-stack.ts
Updates the nag suppressions for CDK Bucket Deployment. 
=> fix: Updated cdk-nag suppression

infra/lib/infra-stack.ts
No previous attachment between user name and user group so dependency was added.
=> fix: congitoUsername --> cognitoUsername, added dependency to userGroupAttachment

backend/backend/handlers/auth/__init__.py, backend/backend/handlers/auth/groups.py, backend/backend/handlers/metadata/create.py
Resolved a couple of issues related to new authorization functionality.
=> Resolved a couple of issues related to new authorization functionality.

backend/backend/handlers/assets/assetService.py, backend/backend/handlers/assets/uploadAsset.py, backend/backend/models/assets.py, infra/package-lock.json, web/src/pages/AssetUpload.tsx, web/src/pages/AssetUpload/onSubmit.ts
*Issue #, if available:*
1. Removing workflow selection from asset upload
2. Fixing #97 
=> Rel 1.4 fixes

web/src/pages/auth/GroupPermissionsTable.tsx
- remove the aspirational permissions menu
- switch the group dropdown to an input so that any value may be provided
=> fix: simplify auth constraints screen

backend/backend/handlers/workflows/createWorkflow.py, infra/lib/api-builder.ts, infra/lib/infra-stack.ts, infra/lib/lambdaBuilder/workflowFunctions.ts
=> FIX: workflows with the same name in different stack

.github/workflows/ci.yml, web/package.json
Changes ci.yml to use a new build target for the web folder with settings to build using less memory
=> fix: web ci build with settings for low memory

web/customInstalls/potree/Potree-Fork_f6ac2d3b.patch
Removed global CSS rules from Potree CSS that were causing side effects to the VAMS styling.
=> Removed global CSS from potree.css

web/src/components/selectors/AssetSelector.js
=> FIX: 3D Model Viewer menu item not showing any assets
